name: 'Init environment'
description: 'Install dependencies'

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: pip install -r requirements-dev.txt && pip install . && npm install
      shell: bash
